accounts:
  europe: <api key>
  north-america: <api key>
clusters:
   ocp-eu:
     region: eu-gb
     resourceGroup: cloudnative-squad
     cluster: learning-ocp4-cluster
     account: europe
   iks-na:
     region: us-east
     resourceGroup: cloudnative-squad
     cluster: learning-iks-cluster
     account: north-america
